dump:
  description: "Dump free@home XML configuration to config folder"

monitor:
  description: "Monitor free@home XML messages and dump to file in config folder"
  fields:
    duration:
      description: "How long we should listen for updates (in seconds)"
      example: "5"
      duration: "5"

cover_force_position:
  description: "Force a cover into a specific position, i.e. open or closed."
  fields:
    entity_id:
      description: Name(s) of the cover entities you want to control
      example: "cover.kitchen"
    forced_position:
      description: Position you want the cover to be in. Supported positions are open, closed and none.
      example: "closed"

thermostat_temperature_correction:
  description: "Change temperature correction for a thermostat"
  fields:
    entity_id:
      description: Name(s) of the thermostat entities you want to control
      example: "climate.kitchen"
    temperature_correction:
      description: Desired temperature_correction. Supportes signed load values.
      example: "-1.0"

